import axios from 'axios';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

class DownloadService {
  async downloadPermitPDF(permit: any) {
    try {
      const pdf = new jsPDF();
      const margin = 20;
      let yPosition = margin;

      // Header
      pdf.setFontSize(20);
      pdf.setFont('helvetica', 'bold');
      pdf.text('WORK PERMIT TO WORK (PTW)', margin, yPosition);
      yPosition += 15;

      // Permit Details
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Permit Number: ${permit.permitNumber}`, margin, yPosition);
      yPosition += 8;
      pdf.text(`Status: ${permit.status.toUpperCase()}`, margin, yPosition);
      yPosition += 8;
      pdf.text(`Plant: ${permit.plantId?.name || 'N/A'}`, margin, yPosition);
      yPosition += 15;

      // Work Description
      pdf.setFont('helvetica', 'bold');
      pdf.text('WORK DESCRIPTION:', margin, yPosition);
      yPosition += 8;
      pdf.setFont('helvetica', 'normal');
      const workDescLines = pdf.splitTextToSize(permit.workDescription || '', 170);
      pdf.text(workDescLines, margin, yPosition);
      yPosition += workDescLines.length * 5 + 10;

      // Permit Types
      pdf.setFont('helvetica', 'bold');
      pdf.text('PERMIT TYPES:', margin, yPosition);
      yPosition += 8;
      pdf.setFont('helvetica', 'normal');
      pdf.text((permit.types || []).join(', '), margin, yPosition);
      yPosition += 15;

      // Schedule
      pdf.setFont('helvetica', 'bold');
      pdf.text('SCHEDULE:', margin, yPosition);
      yPosition += 8;
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Start: ${format(new Date(permit.schedule?.startDate), 'MMM dd, yyyy HH:mm')}`, margin, yPosition);
      yPosition += 6;
      pdf.text(`End: ${format(new Date(permit.schedule?.endDate), 'MMM dd, yyyy HH:mm')}`, margin, yPosition);
      yPosition += 15;

      // Hazards
      if (permit.hazards && permit.hazards.length > 0) {
        pdf.setFont('helvetica', 'bold');
        pdf.text('IDENTIFIED HAZARDS:', margin, yPosition);
        yPosition += 8;
        pdf.setFont('helvetica', 'normal');
        
        permit.hazards.forEach((hazard: any, index: number) => {
          pdf.text(`${index + 1}. ${hazard.type}: ${hazard.mitigation}`, margin, yPosition);
          yPosition += 6;
        });
        yPosition += 10;
      }

      // PPE Requirements
      if (permit.ppe && permit.ppe.length > 0) {
        pdf.setFont('helvetica', 'bold');
        pdf.text('PPE REQUIREMENTS:', margin, yPosition);
        yPosition += 8;
        pdf.setFont('helvetica', 'normal');
        
        const requiredPPE = permit.ppe.filter((item: any) => item.required);
        requiredPPE.forEach((item: any, index: number) => {
          pdf.text(`${index + 1}. ${item.item}`, margin, yPosition);
          yPosition += 6;
        });
        yPosition += 10;
      }

      // Safety Checklist
      if (permit.safetyChecklist && permit.safetyChecklist.length > 0) {
        pdf.setFont('helvetica', 'bold');
        pdf.text('SAFETY CHECKLIST:', margin, yPosition);
        yPosition += 8;
        
        permit.safetyChecklist.forEach((item: any, index: number) => {
          const status = item.checked ? '✓' : '✗';
          pdf.text(`${status} ${item.item}`, margin, yPosition);
          yPosition += 6;
          if (yPosition > 270) {
            pdf.addPage();
            yPosition = margin;
          }
        });
        yPosition += 10;
      }

      // Approvals
      if (permit.approvals && permit.approvals.length > 0) {
        pdf.setFont('helvetica', 'bold');
        pdf.text('APPROVALS:', margin, yPosition);
        yPosition += 8;
        
        permit.approvals.forEach((approval: any, index: number) => {
          pdf.setFont('helvetica', 'normal');
          pdf.text(`Step ${approval.step}: ${approval.label} - ${approval.status.toUpperCase()}`, margin, yPosition);
          yPosition += 6;
          if (approval.timestamp) {
            pdf.text(`Date: ${format(new Date(approval.timestamp), 'MMM dd, yyyy HH:mm')}`, margin + 10, yPosition);
            yPosition += 6;
          }
          if (approval.comments) {
            pdf.text(`Comments: ${approval.comments}`, margin + 10, yPosition);
            yPosition += 6;
          }
          yPosition += 5;
        });
      }

      // Footer
      pdf.setFontSize(8);
      pdf.text('Generated by Safety Management System', margin, 280);
      pdf.text(`Generated on: ${format(new Date(), 'MMM dd, yyyy HH:mm')}`, margin, 285);

      // Save the PDF
      pdf.save(`permit-${permit.permitNumber}.pdf`);
      return true;
    } catch (error) {
      console.error('Error generating PDF:', error);
      throw error;
    }
  }

  async downloadPermitExcel(permit: any) {
    try {
      const workbook = XLSX.utils.book_new();

      // Main permit data
      const permitData = [
        ['Permit Number', permit.permitNumber],
        ['Status', permit.status],
        ['Plant', permit.plantId?.name || ''],
        ['Work Description', permit.workDescription],
        ['Permit Types', (permit.types || []).join(', ')],
        ['Start Date', format(new Date(permit.schedule?.startDate), 'MMM dd, yyyy HH:mm')],
        ['End Date', format(new Date(permit.schedule?.endDate), 'MMM dd, yyyy HH:mm')],
        ['Requested By', permit.requestedBy?.name || ''],
        ['Created Date', format(new Date(permit.createdAt), 'MMM dd, yyyy HH:mm')]
      ];

      const permitSheet = XLSX.utils.aoa_to_sheet(permitData);
      XLSX.utils.book_append_sheet(workbook, permitSheet, 'Permit Details');

      // Hazards sheet
      if (permit.hazards && permit.hazards.length > 0) {
        const hazardData = [
          ['Type', 'Mitigation']
        ];
        permit.hazards.forEach((hazard: any) => {
          hazardData.push([hazard.type, hazard.mitigation]);
        });
        const hazardSheet = XLSX.utils.aoa_to_sheet(hazardData);
        XLSX.utils.book_append_sheet(workbook, hazardSheet, 'Hazards');
      }

      // PPE sheet
      if (permit.ppe && permit.ppe.length > 0) {
        const ppeData = [
          ['Item', 'Required']
        ];
        permit.ppe.forEach((item: any) => {
          ppeData.push([item.item, item.required ? 'Yes' : 'No']);
        });
        const ppeSheet = XLSX.utils.aoa_to_sheet(ppeData);
        XLSX.utils.book_append_sheet(workbook, ppeSheet, 'PPE Requirements');
      }

      // Safety Checklist sheet
      if (permit.safetyChecklist && permit.safetyChecklist.length > 0) {
        const checklistData = [
          ['Item', 'Checked', 'Remarks']
        ];
        permit.safetyChecklist.forEach((item: any) => {
          checklistData.push([
            item.item,
            item.checked ? 'Yes' : 'No',
            item.remarks || ''
          ]);
        });
        const checklistSheet = XLSX.utils.aoa_to_sheet(checklistData);
        XLSX.utils.book_append_sheet(workbook, checklistSheet, 'Safety Checklist');
      }

      // Approvals sheet
      if (permit.approvals && permit.approvals.length > 0) {
        const approvalData = [
          ['Step', 'Role', 'Status', 'Approver', 'Comments', 'Date']
        ];
        permit.approvals.forEach((approval: any) => {
          approvalData.push([
            approval.step,
            approval.role,
            approval.status,
            approval.approver?.name || '',
            approval.comments || '',
            approval.timestamp ? format(new Date(approval.timestamp), 'MMM dd, yyyy HH:mm') : ''
          ]);
        });
        const approvalSheet = XLSX.utils.aoa_to_sheet(approvalData);
        XLSX.utils.book_append_sheet(workbook, approvalSheet, 'Approvals');
      }

      // Save the Excel file
      XLSX.writeFile(workbook, `permit-${permit.permitNumber}.xlsx`);
      return true;
    } catch (error) {
      console.error('Error generating Excel:', error);
      throw error;
    }
  }

  async downloadPermitList(permits: any[], filters: any = {}) {
    try {
      const workbook = XLSX.utils.book_new();
      
      // Summary sheet
      const summaryData = [
        ['Permit List Report'],
        ['Generated On', format(new Date(), 'MMM dd, yyyy HH:mm')],
        ['Total Permits', permits.length],
        ['']
      ];

      if (filters.status) summaryData.push(['Filter - Status', filters.status]);
      if (filters.type) summaryData.push(['Filter - Type', filters.type]);
      if (filters.plantId) summaryData.push(['Filter - Plant', filters.plantId]);

      summaryData.push([''], ['Permit Details:']);

      const headers = [
        'Permit Number',
        'Status',
        'Work Description',
        'Types',
        'Plant',
        'Start Date',
        'End Date',
        'Requested By',
        'Created Date'
      ];

      summaryData.push(headers);

      permits.forEach((permit: any) => {
        summaryData.push([
          permit.permitNumber,
          permit.status,
          permit.workDescription,
          (permit.types || []).join(', '),
          permit.plantId?.name || '',
          format(new Date(permit.schedule?.startDate), 'MMM dd, yyyy'),
          format(new Date(permit.schedule?.endDate), 'MMM dd, yyyy'),
          permit.requestedBy?.name || '',
          format(new Date(permit.createdAt), 'MMM dd, yyyy')
        ]);
      });

      const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
      
      // Set column widths
      summarySheet['!cols'] = [
        { width: 20 }, { width: 15 }, { width: 40 }, { width: 20 },
        { width: 20 }, { width: 15 }, { width: 15 }, { width: 20 }, { width: 15 }
      ];

      XLSX.utils.book_append_sheet(workbook, summarySheet, 'Permit List');

      // Save the Excel file
      const fileName = `permit-list-${format(new Date(), 'yyyy-MM-dd')}.xlsx`;
      XLSX.writeFile(workbook, fileName);
      return true;
    } catch (error) {
      console.error('Error generating permit list Excel:', error);
      throw error;
    }
  }

  async downloadPermitWord(permit: any) {
    // For Word document, we'll create HTML and let the browser handle it
    const htmlContent = this.generatePermitHTML(permit);
    const blob = new Blob([htmlContent], { type: 'application/msword' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `permit-${permit.permitNumber}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
    return true;
  }

  private generatePermitHTML(permit: any): string {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Permit ${permit.permitNumber}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
          .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
          .section { margin-bottom: 30px; }
          .section-title { font-size: 16px; font-weight: bold; color: #333; border-bottom: 1px solid #ccc; padding-bottom: 5px; margin-bottom: 15px; }
          .field { margin-bottom: 10px; }
          .field-label { font-weight: bold; display: inline-block; width: 120px; }
          .checklist-item { margin: 5px 0; }
          .signature-section { margin-top: 50px; border-top: 1px solid #ccc; padding-top: 20px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>WORK PERMIT TO WORK (PTW)</h1>
          <p>Permit Number: ${permit.permitNumber}</p>
          <p>Status: ${permit.status.toUpperCase()}</p>
        </div>

        <div class="section">
          <div class="section-title">PERMIT DETAILS</div>
          <div class="field"><span class="field-label">Plant:</span> ${permit.plantId?.name || 'N/A'}</div>
          <div class="field"><span class="field-label">Area:</span> ${permit.location?.area || 'N/A'}</div>
          <div class="field"><span class="field-label">Types:</span> ${(permit.types || []).join(', ')}</div>
          <div class="field"><span class="field-label">Start Date:</span> ${format(new Date(permit.schedule?.startDate), 'MMM dd, yyyy HH:mm')}</div>
          <div class="field"><span class="field-label">End Date:</span> ${format(new Date(permit.schedule?.endDate), 'MMM dd, yyyy HH:mm')}</div>
        </div>

        <div class="section">
          <div class="section-title">WORK DESCRIPTION</div>
          <p>${permit.workDescription || 'N/A'}</p>
        </div>

        ${permit.hazards && permit.hazards.length > 0 ? `
          <div class="section">
            <div class="section-title">IDENTIFIED HAZARDS</div>
            ${permit.hazards.map((hazard: any, index: number) => `
              <div class="field">${index + 1}. <strong>${hazard.type}:</strong> ${hazard.mitigation}</div>
            `).join('')}
          </div>
        ` : ''}

        ${permit.ppe && permit.ppe.length > 0 ? `
          <div class="section">
            <div class="section-title">PPE REQUIREMENTS</div>
            ${permit.ppe.filter((item: any) => item.required).map((item: any, index: number) => `
              <div class="checklist-item">☑ ${item.item}</div>
            `).join('')}
          </div>
        ` : ''}

        ${permit.safetyChecklist && permit.safetyChecklist.length > 0 ? `
          <div class="section">
            <div class="section-title">SAFETY CHECKLIST</div>
            ${permit.safetyChecklist.map((item: any) => `
              <div class="checklist-item">${item.checked ? '☑' : '☐'} ${item.item}</div>
            `).join('')}
          </div>
        ` : ''}

        ${permit.approvals && permit.approvals.length > 0 ? `
          <div class="section">
            <div class="section-title">APPROVALS</div>
            ${permit.approvals.map((approval: any) => `
              <div class="field">
                <strong>Step ${approval.step} - ${approval.label}:</strong> ${approval.status.toUpperCase()}
                ${approval.timestamp ? `<br><small>Date: ${format(new Date(approval.timestamp), 'MMM dd, yyyy HH:mm')}</small>` : ''}
                ${approval.comments ? `<br><small>Comments: ${approval.comments}</small>` : ''}
              </div>
            `).join('')}
          </div>
        ` : ''}

        <div class="signature-section">
          <p><strong>Generated by Safety Management System</strong></p>
          <p>Generated on: ${format(new Date(), 'MMM dd, yyyy HH:mm')}</p>
        </div>
      </body>
      </html>
    `;
  }
}

export default new DownloadService();